# Generated by Django 6.0.6 on 2026-06-04 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_privacy_policy', models.BooleanField(default=False)),
                ('has_cookie_banner', models.BooleanField(default=False)),
                ('has_google_analytics', models.BooleanField(default=False)),
                ('has_facebook_pixel', models.BooleanField(default=False)),
                ('has_other_trackers', models.BooleanField(default=False)),
                ('other_trackers_found', models.JSONField(default=list)),
                ('is_https', models.BooleanField(default=False)),
                ('has_contact_info', models.BooleanField(default=False)),
                ('raw_html', models.TextField(blank=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('error', models.TextField(blank=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scan_result', to='orders.order')),
            ],
        ),
    ]
