# Generated by Django 6.0.6 on 2026-06-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='cdn_found',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='cms_detected',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='has_cdn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='has_contact_form',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='has_content_security_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='has_cookie_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='has_cookie_preferences_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='has_data_retention_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='has_data_subject_rights',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='has_dpo_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='has_form_consent_checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='has_live_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='has_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='has_mixed_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='has_newsletter_signup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='has_payment_processor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='has_referrer_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='has_terms_and_conditions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='has_unsubscribe_mechanism',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='has_x_content_type_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='has_x_frame_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='live_chat_tools_found',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='payment_processors_found',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='privacy_policy_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='privacy_policy_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='terms_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='terms_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
