# Generated by Django 6.0.6 on 2026-06-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_scanresult_cdn_found_scanresult_cms_detected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='ecommerce_platform',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='has_ecommerce',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='has_social_embeds',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='social_embeds_found',
            field=models.JSONField(default=list),
        ),
    ]
