# Generated by Django 6.0.6 on 2026-06-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_scanresult_ecommerce_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='privacy_policy_ai_analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='terms_ai_analysis',
            field=models.TextField(blank=True),
        ),
    ]
