# Generated by Django 6.0.6 on 2026-06-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='referrer',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_content',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_term',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
