# Generated by Django 6.0.6 on 2026-06-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_amount_paid_order_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('scanning', 'Scanning'), ('analysing', 'Analysing'), ('generating', 'Generating Report'), ('emailing', 'Sending Email'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
