# Generated by Django 6.0.6 on 2026-06-09 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_free_result_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rescan_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescans', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='report_type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('rescan', 'Re-scan')], default='free', max_length=10),
        ),
    ]
